LIB =	common

SRCS =				\
	blowfish		\
	common			\
	format			\
	tasks			\
	timer			\
	timestamp		\
	strutil			\
	kbeversion		\
	kbekey			\
	md5				\
	sha1			\
	base64			\
	rsa				\
	memorystream

include $(KBE_SRC_ROOT)/kbe/src/build/common.mak
