LIB =	navigation

SRCS =					\
	DetourAlloc			\
	DetourCommon			\
	DetourNavMesh			\
	DetourNavMeshBuilder		\
	DetourNavMeshQuery		\
	DetourNode			\
	DetourCrowd			\
	DetourLocalBoundary		\
	DetourObstacleAvoidance		\
	DetourPathCorridor		\
	DetourPathQueue			\
	DetourProximityGrid		\
	DetourTileCache			\
	DetourTileCacheBuilder		\
	navigation			\
	navigation_handle		\
	navigation_tile_handle		\
	navigation_mesh_handle		\
	Recast				\
	RecastAlloc			\
	RecastArea			\
	RecastContour			\
	RecastFilter			\
	RecastLayers			\
	RecastMesh			\
	RecastMeshDetail		\
	RecastRasterization		\
	RecastRegion

include $(KBE_SRC_ROOT)/kbe/src/build/common.mak
