LIB =	sigar

CSRCS =				\
	sigar			\
	sigar_cache		\
	sigar_fileinfo		\
	sigar_format		\
	sigar_getline		\
	sigar_ptql		\
	sigar_signal		\
	sigar_util		\
	linux_sigar

include $(KBE_SRC_ROOT)/kbe/src/build/common.mak
