LIB =	g3dlite

SRCS =				\
	AABox			\
	Box			\
	Crypto			\
	format			\
	Matrix3			\
	Plane			\
	System			\
	Triangle		\
	Vector3			\
	Vector4

include $(KBE_SRC_ROOT)/kbe/src/build/common.mak
