LIB =	tmxparser

SRCS =				\
	base64			\
	TmxEllipse		\
	TmxImage		\
	TmxImageLayer		\
	TmxLayer		\
	TmxMap			\
	TmxObject		\
	TmxObjectGroup		\
	TmxPolygon		\
	TmxPolyline		\
	TmxPropertySet		\
	TmxTile			\
	TmxTileset		\
	TmxUtil			


include $(KBE_SRC_ROOT)/kbe/src/build/common.mak
